name: Events Demo 1
on: 
  pull_request: 
    types:
      - opened
  workflow_dispatch: 
  # push:
  #   branches: 
  #     - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v6
      - name: build client
        run: gcc -o client client.c
      - name: build server
        run: gcc -o server server.c
      - name: Deploy project
        run: echo "Deploying..."