name: Deploy website
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: build client
        run: gcc -o client client.c
      - name: build server
        run: gcc -o server server.c
        
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: build client
        run: gcc -o client client.c
      - name: build server
        run: gcc -o server server.c
      - name: publish file names
        id: publish
        run: find ./client -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
      - name: upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: |
            server
            client
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: get buils
        uses: actions/download-artifact@v4
        with: 
          name: dist-files
      - name: output content
        run: ls
      - name: output file name
        run: echo "${{needs.build.outputs.script-file}}"
      - name: Deploy
        run: echo "Deploying..."
