name: output information
on: workflow_dispatch # [workflow_dispatch, issues]
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: output my github contex
        run: echo "${{toJson(github) }}"
