name: resusle deply
on: 
  workflow_call: 
    inputs:
      artifact-name: 
        description: the name 
        required: false
        default: dist
        type: string
    
    outputs:
      results:
        description: the result of dplmnt opeartion
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}

    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/download-artifact@v4
        with: 
          name: ${{ inputs.artifact-name }}
      - name: list files
        run: ls
      - name: output info
        run: echo "deply and uplading"
      - name: set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT

