name: test project
on: workflow_dispatch # [push, workflow_dispatch]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: build client
        run: gcc -o client client.c

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: build server
        run: gcc -o server server.c
      - name: deploy
        run: echo "Deploying"

